// قائمة الكليات/الاختصاصات — المصدر الوحيد للواجهة، مطابقة بالحرف لـ enum College
// بالباك (app/models/enums.py). الأسماء العربية مأخوذة من نفس المصدر.
// ملاحظة: not_chosen_yet هي قيمة منطقية خاصة (لم يقرر الطالب بعد) ولا تُعرض بالقائمة.
export const COLLEGE_OPTIONS = [
  { id: 'medicine', name: 'الطب البشري' },
  { id: 'pharmacy', name: 'الصيدلة' },
  { id: 'dentistry', name: 'طب الأسنان' },
  { id: 'health_labs', name: 'علوم صحيّة مخابر' },
  { id: 'health_nutrition', name: 'علوم صحيّة تغذية' },
  { id: 'health_physiotherapy', name: 'علوم صحية علاج فيزيائي' },
  { id: 'mech_power_eng', name: 'هندسة قوى ميكانيكية' },
  { id: 'control_computer_eng', name: 'هندسة تحكم آلي وحواسيب' },
  { id: 'energy_eng', name: 'هندسة طاقة' },
  { id: 'mechatronics', name: 'ميكاترونك' },
  { id: 'telecom_eng', name: 'هندسة اتصالات' },
  { id: 'metallurgy_eng', name: 'هندسة المعادن' },
  { id: 'design_production_eng', name: 'هندسة التصميم والإنتاج' },
  { id: 'petroleum_eng', name: 'هندسة بيتروليّة' },
  { id: 'food_eng', name: 'هندسة غذائية' },
  { id: 'chemical_eng', name: 'هندسة كيميائية' },
  { id: 'textile_eng', name: 'هندسة الغزل والنسيج' },
  { id: 'civil', name: 'هندسة مدنيّة' },
  { id: 'tourism', name: 'سياحة' },
  { id: 'architecture', name: 'هندسة معماريّة' },
  { id: 'music', name: 'موسيقا' },
  { id: 'physics', name: 'فيزياء' },
  { id: 'mathematics', name: 'رياضيات' },
  { id: 'statistics', name: 'إحصاء' },
  { id: 'biology', name: 'علم الحياة بيولوجيا' },
  { id: 'geology', name: 'علم الحياة جيولوجيا' },
  { id: 'chemistry', name: 'كيمياء' },
  { id: 'economics', name: 'اقتصاد' },
  { id: 'informatics', name: 'هندسة معلوماتية' },
  { id: 'applied_science', name: 'كلية تطبيقية' },
  { id: 'arabic', name: 'لغة عربية' },
  { id: 'english', name: 'لغة انكليزية' },
  { id: 'french', name: 'لغة فرنسية' },
  { id: 'persian', name: 'لغة فارسية' },
  { id: 'history', name: 'تاريخ' },
  { id: 'philosophy', name: 'فلسفة' },
  { id: 'agriculture', name: 'هندسة زراعية' },
  { id: 'law', name: 'حقوق' },
  { id: 'curricula', name: 'مناهج وطرق تدريس' },
  { id: 'psychology', name: 'علم نفس' },
  { id: 'kindergarten', name: 'رياض أطفال' },
  { id: 'psychological_counseling', name: 'إرشاد نفسي' },
  { id: 'class_teacher', name: 'معلم صف' },
  { id: 'sharia', name: 'شريعة' },
  { id: 'institute_agriculture', name: 'معهد تقاني زراعي' },
  { id: 'institute_desert_affairs', name: 'معهد تقاني لشؤون البادية والتصحر' },
  { id: 'institute_engineering', name: 'معهد تقاني هندسي' },
  { id: 'institute_health', name: 'معهد تقاني صحي' },
  { id: 'institute_dentistry', name: 'معهد تقاني طب اسنان' },
  { id: 'institute_applied_industries', name: 'معهد تقاني صناعات تطبيقية' },
  { id: 'institute_computer', name: 'معهد تقاني حاسوب' },
];