// بيانات خريطة الجامعة — 12 مبنى + 4 بوابات
// x/y = مركز النص (قابل للنقر) بالنسبة المئوية من الصورة (1080×1080)
// w/h = مساحة النص فقط — الإطار غير قابل للنقر

export const MAP_BUILDINGS = [
  {
    id: 'hemk',
    name: 'كليات الهمك',
    type: 'building',
    x: 31.2,
    y: 16.4,
    w: 13,
    h: 8.5,
    description: 'تضم كليتَي الهندسة الميكانيكية والكهربائية والهندسة البترولية والكيميائية',
    groups: [
      {
        name: 'هندسة ميكانيكية وكهربائية',
        items: [
          'هندسة إلكترون',
          'هندسة معادن',
          'هندسة ميكاترونيك',
          'هندسة تحكم آلي وحواسيب',
          'هندسة تصميم وإنتاج',
          'هندسة قوى ميكانيكية',
          'هندسة طاقة كهربائية',
        ],
      },
      {
        name: 'هندسة بترولية وكيميائية',
        items: ['هندسة غذائية', 'هندسة بترولية', 'هندسة كيميائية', 'هندسة غزل ونسيج'],
      },
    ],
  },
  {
    id: 'medical',
    name: 'الكليات الطبية',
    type: 'building',
    x: 61,
    y: 13.9,
    w: 11.5,
    h: 7,
    description: 'الكتلة الطبية بالجامعة',
    colleges: ['طب بشري', 'طب أسنان', 'صيدلة', 'علوم صحية'],
  },
  {
    id: 'law',
    name: 'كلية الحقوق',
    type: 'building',
    x: 59.3,
    y: 24,
    w: 8.5,
    h: 4.5,
    description: '',
    colleges: ['حقوق'],
  },
  {
    id: 'union-old',
    name: 'مبنى الاتحاد القديم',
    type: 'building',
    x: 59.5,
    y: 33.8,
    w: 9,
    h: 4.5,
    description: 'اتحاد الطلبة هي الجهة الممثلة للطلاب داخل الجامعة',
    colleges: [],
  },
  {
    id: 'civil-eng',
    name: 'كلية الهندسة المدنية',
    type: 'building',
    x: 34.7,
    y: 41.4,
    w: 9.5,
    h: 6.5,
    description: '',
    colleges: ['هندسة مدنية', 'سياحة'],
  },
  {
    id: 'science',
    name: 'كلية العلوم',
    type: 'building',
    x: 53.4,
    y: 41.9,
    w: 9.5,
    h: 7,
    description: '',
    colleges: ['هندسة معلوماتية', 'اقتصاد', 'تطبيقية', 'معهد تقاني حاسوب'],
    groups: [
      {
        name: 'علوم',
        items: ['فيزيا', 'كيميا', 'علوم طبيعية', 'رياضيات', 'إحصاء', 'جيولوجيا'],
      },
    ],
  },
  {
    id: 'sharia',
    name: 'كلية الشريعة',
    type: 'building',
    x: 67,
    y: 48.5,
    w: 7.5,
    h: 6.5,
    description: '',
    colleges: ['شريعة'],
  },
  {
    id: 'arch-eng',
    name: 'كلية الهندسة المعمارية',
    type: 'building',
    x: 34.7,
    y: 53.9,
    w: 9.5,
    h: 6.5,
    description: '',
    colleges: ['هندسة العمارة', 'الموسيقى'],
  },
  {
    id: 'adab',
    name: 'كلية الآداب',
    type: 'building',
    x: 53.9,
    y: 54.6,
    w: 10,
    h: 7.5,
    description: '',
    colleges: ['لغة إنجليزية', 'لغة عربية', 'لغة فارسية', 'لغة فرنسية', 'فلسفة', 'تاريخ', 'المعهد العالي للغات'],
    featured: true,
  },
  {
    id: 'student-union',
    name: 'مبنى اتحاد الطلبة',
    type: 'building',
    x: 34.7,
    y: 66.4,
    w: 9.5,
    h: 7,
    description: 'اتحاد الطلبة هي الجهة الممثلة للطلاب داخل الجامعة',
    colleges: [],
  },
  {
    id: 'admin',
    name: 'الإدارة المركزية',
    type: 'building',
    x: 53.7,
    y: 71.3,
    w: 10,
    h: 6.5,
    description: 'إدارة الجامعة',
    colleges: [],
  },
  {
    id: 'agri',
    name: 'كلية الهندسة الزراعية',
    type: 'building',
    x: 12.2,
    y: 57.1,
    w: 12,
    h: 8.5,
    description: '',
    colleges: ['هندسة زراعة'],
    groups: [
      {
        name: 'التربية',
        items: ['مناهج', 'رياض أطفال', 'علم نفس', 'إرشاد نفسي', 'معلم صف'],
      },
      {
        name: 'معاهد',
        items: ['معهد هندسي', 'المعهد التقاني لشؤون البادية والتصحر'],
      },
    ],
  },
  {
    id: 'gate-science',
    name: 'باب العلوم',
    type: 'gate',
    side: 'right',
    x: 81,
    y: 26.2,
    w: 10,
    h: 8,
    description: 'بوابة مدخل الجامعة',
    colleges: [],
  },
  {
    id: 'gate-adab',
    name: 'باب الآداب',
    type: 'gate',
    side: 'right',
    x: 81,
    y: 65.5,
    w: 10,
    h: 8,
    description: 'بوابة مدخل الجامعة',
    colleges: [],
  },
  {
    id: 'gate-main',
    name: 'الباب الرئيسي',
    type: 'gate',
    side: 'bottom',
    x: 66.2,
    y: 93.5,
    w: 10,
    h: 8,
    description: 'بوابة مدخل الجامعة',
    colleges: [],
  },
  {
    id: 'gate-education',
    name: 'باب الزراعة',
    type: 'gate',
    side: 'bottom',
    x: 32.4,
    y: 93.5,
    w: 10,
    h: 8,
    description: 'بوابة مدخل الجامعة',
    colleges: [],
  },
];
