// بيانات خريطة الجامعة — 12 مبنى + 4 بوابات
// الإحداثيات بالنسبة المئوية من أبعاد الصورة (1080×1080)
// التعديل هنا لا يحتاج لمس أي كود آخر

export const MAP_BUILDINGS = [
  {
    id: 'hemk',
    name: 'كليات الهمك',
    type: 'building',
    x: 31,
    y: 16,
    description: 'تضم كليتَي الهندسة الميكانيكية والكهربائية والهندسة البترولية والكيميائية',
    groups: [
      {
        name: 'هندسة ميكانيكية وكهربائية',
        items: [
          'هندسة إلكترون',
          'هندسة معادن',
          'هندسة ميكاترونيك',
          'هندسة تحكم آلي وحواسيب',
          'هندسة تصميم وإنتاج',
          'هندسة قوى ميكانيكية',
          'هندسة طاقة كهربائية',
        ],
      },
      {
        name: 'هندسة بترولية وكيميائية',
        items: ['هندسة غذائية', 'هندسة بترولية', 'هندسة كيميائية', 'هندسة غزل ونسيج'],
      },
    ],
  },
  {
    id: 'medical',
    name: 'الكليات الطبية',
    type: 'building',
    x: 61,
    y: 13,
    description: 'الكتلة الطبية بالجامعة',
    colleges: ['طب بشري', 'طب أسنان', 'صيدلة', 'علوم صحية'],
  },
  {
    id: 'law',
    name: 'كلية الحقوق',
    type: 'building',
    x: 59,
    y: 21,
    description: '',
    colleges: ['حقوق'],
  },
  {
    id: 'union-old',
    name: 'مبنى الاتحاد القديم',
    type: 'building',
    x: 58.5,
    y: 33,
    description: 'اتحاد الطلبة هي الجهة الممثلة للطلاب داخل الجامعة',
    colleges: [],
  },
  {
    id: 'civil-eng',
    name: 'كلية الهندسة المدنية',
    type: 'building',
    x: 34,
    y: 42,
    description: '',
    colleges: ['هندسة مدنية', 'سياحة'],
  },
  {
    id: 'science',
    name: 'كلية العلوم',
    type: 'building',
    x: 53,
    y: 42,
    description: '',
    colleges: ['هندسة معلوماتية', 'اقتصاد', 'تطبيقية', 'معهد تقاني حاسوب'],
    groups: [
      {
        name: 'علوم',
        items: ['فيزيا', 'كيميا', 'علوم طبيعية', 'رياضيات', 'إحصاء', 'جيولوجيا'],
      },
    ],
  },
  {
    id: 'sharia',
    name: 'كلية الشريعة',
    type: 'building',
    x: 69,
    y: 49,
    description: '',
    colleges: [],
  },
  {
    id: 'arch-eng',
    name: 'كلية الهندسة المعمارية',
    type: 'building',
    x: 34,
    y: 53.5,
    description: '',
    colleges: ['هندسة معمارية', 'موسيقى'],
  },
  {
    id: 'adab',
    name: 'كلية الآداب',
    type: 'building',
    x: 53.5,
    y: 54.5,
    description: '',
    colleges: ['لغة إنجليزية', 'لغة عربية', 'لغة فارسية', 'لغة فرنسية', 'فلسفة', 'تاريخ', 'المعهد العالي للغات'],
    featured: true,
  },
  {
    id: 'student-union',
    name: 'مبنى اتحاد الطلبة',
    type: 'building',
    x: 34,
    y: 65.5,
    description: 'اتحاد الطلبة هي الجهة الممثلة للطلاب داخل الجامعة',
    colleges: [],
  },
  {
    id: 'admin',
    name: 'الإدارة المركزية',
    type: 'building',
    x: 53.5,
    y: 70,
    description: 'إدارة الجامعة',
    colleges: [],
  },
  {
    id: 'agri',
    name: 'كلية الهندسة الزراعية',
    type: 'building',
    x: 11.5,
    y: 60.5,
    description: '',
    colleges: ['هندسة زراعة'],
    groups: [
      {
        name: 'التربية',
        items: ['مناهج', 'رياض أطفال', 'علم نفس', 'إرشاد نفسي', 'معلم صف'],
      },
    ],
  },
  {
    id: 'gate-science',
    name: 'باب العلوم',
    type: 'gate',
    x: 82.5,
    y: 26.5,
    description: '',
    colleges: [],
  },
  {
    id: 'gate-adab',
    name: 'باب الآداب',
    type: 'gate',
    x: 82.5,
    y: 63.5,
    description: '',
    colleges: [],
  },
  {
    id: 'gate-main',
    name: 'الباب الرئيسي',
    type: 'gate',
    x: 64.5,
    y: 92,
    description: '',
    colleges: [],
  },
  {
    id: 'gate-education',
    name: 'باب التربية',
    type: 'gate',
    x: 28,
    y: 92,
    description: '',
    colleges: [],
  },
];
